### ISSUE TITLE
SqlTzLoader.exe -c"Server=YourServerName;Database=YourDatabaseName;Trusted_Connection=True"

### ISSUE THREAD

**Issue by nibavsyed** [mj1856/SqlServerTimeZoneSupport#19]
SqlTzLoader.exe -c"Server=YourServerName;Database=YourDatabaseName;Trusted_Connection=True"
While using this connection string like 

<add name="tzdb" connectionString= SqlTzLoader.exe -c"Server=SYED-PC\MSSQLSERVER2008;Database=DbMigration;Trusted_Connection=True"/>

**Comment by nibavsyed** [comment]
i am getting error

**Comment by aculver28** [comment]
I'm having the same issue as well. No format of the connection string is working and the verbose option doesn't work either. Here's the stack trace:

```
Unhandled Exception: System.Data.SqlClient.SqlException: A network-related or in
stance-specific error occurred while establishing a connection to SQL Server. Th
e server was not found or was not accessible. Verify that the instance name is c
orrect and that SQL Server is configured to allow remote connections. (provider:
 SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdent
ity identity, SqlConnectionString connectionOptions, SqlCredential credential, O
bject providerInfo, String newPassword, SecureString newSecurePassword, Boolean
redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData r
econnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTra
nsientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOp
tions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConn
ectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)

   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConn
ectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConne
ctionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owning
Object, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection o
wningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection
)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection ow
ningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean o
nlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& co
nnection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at SqlTzLoader.Program.<WriteZonesAsync>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at SqlTzLoader.Program.<MainAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Threading.AsyncPump.Run(Func`1 func)
   at SqlTzLoader.Program.Main(String[] args)
```

**Comment by tolian49** [comment]
I am experiencing this same problem now. Was able to run the job ~1 year ago.

**Comment by Firanus** [comment]
I was having this same error, but managed to get it working by opening the config .xml file and pasting my connection string into there. Hopefully that helps. :)

**Comment by skiplogic** [comment]
Editing the config file fixed the same issue for me,

**Comment by HolisticDeveloper** [comment]
Looks like this is because the latest release is outdated. See #17.

**Comment by martincheck** [comment]
This issue appears to be resolved now as i managed to connect using just the command line.  Anyone still running into this?
