### ISSUE TITLE
SqlTzLoader.exe fails due to "Proxy Authentication Required"

### ISSUE THREAD

**Issue by dbwench** [mj1856/SqlServerTimeZoneSupport#34]
"Unhandled Exception: System.Net.Http.HttpRequestException: Response status code
does not indicate success: 407 (Proxy Authentication Required).
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NodaTime.CurrentTzdbProvider.<DownloadAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NodaTime.CurrentTzdbProvider.<LoadAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at SqlTzLoader.Program.<MainAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Threading.AsyncPump.Run(Func`1 func)
   at SqlTzLoader.Program.Main(String[] args)"

Any way to get around this?

**Comment by dbwench** [comment]
Nevermind - figured it out
